### ISSUE TITLE
support way to set default value

### ISSUE THREAD

**Issue by badaverse** [mcjohnalds/react-table-drag-select#2]
It's using `new TableDragSelect.Model(x, y)` to create data model.
but it's impossible to set default value.

so I'm using this way to set default value.
```js
let dataModel = new TableDragSelect.Model(x, y);
dataModel._cellsSelected=this.props.data
```

but I'd like to use more simple and effective way.

like 
```js
const array = [ [true,true,true], [false,false,false] ]
let dataModel = new TableDragSelect.ModelFromJS(array)
```
do you have any plan to support this?

**Comment by mcjohnalds** [comment]
I wasn't happy with the API design. I did a total rewrite over the weekend and it's now dead-simple to do what you're asking (see the new readme). Just update to the latest package on npm.

Thanks for opening an issue.

**Comment by MyeongkookKim** [comment]
great. thx!
